Add orange pi 4
GloDroid/glodroid_device pull request #15
Opened 2020-12-18 15:49 UTC by daaaanil81

Support has been added for the board Orange Pi 4, but it needs in the rkbin repository from rockchip.

2020-12-18 16:12 UTC, daaaanil81 commented
1. Change path for ATF bl31 file for Rockchip.
2. Add config files for Rockchip.
3. Change config parameters for fastboot.
4. Change number of sector for written images.
5. Change value of address for bootscript.
6. Change config files for emmc and sd, because in rockchip, emmc is 0, sd is 1.
7. Add created uboot image for rockchip. Rockchip needs binaries from rkbin repository.

2020-12-19 02:02 UTC, rsglobal commented
https://patchwork.kernel.org/project/linux-usb/cover/20201114081247.25063-1-wcheng@codeaurora.org/

2020-12-28 11:21 UTC, rsglobal requested changes

2020-12-28 11:21 UTC, rsglobal commented on platform/common/uboot.config
> +CONFIG_FASTBOOT=y
Can we remove this?

2020-12-28 11:21 UTC, rsglobal commented on platform/tools/gensdimg.sh
> -
Please avoid adding empty lines.

2020-12-28 11:21 UTC, rsglobal commented on platform/tools/gensdimg.sh
> -
ditto

2020-12-28 11:21 UTC, rsglobal commented on platform/tools/gensdimg.sh
> -
ditto

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/bootscript.cpp
> + /*EXTENV(bootargs, " earlycon=uart8250,mmio32,0xff1a0000 swiotlb=1 console=ttyFIQ0")*/
Consider removing commented line

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/uboot.mk
> +RKTRUST_INI = RK3399TRUST.ini
Please use `:=`

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/uboot.mk
> +
drop extra line please

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	dd if=$(UBOOT_OUT)/uboot.img of=$@ seek=16320 # 16320 - 950768
Please change to `$$(( 16384 - 64 ))`

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	#dd if=/dev/null of=$@ bs=1 count=1 seek=$$(( 9216 * 1024 - 64 * 512 )) # 16 744 448 - 16 777 216
Please drop

2020-12-28 11:21 UTC, rsglobal commented on opi4/AndroidProducts.mk
> +# Copyright (C) 2020 Roman Stratiienko (r.stratiienko@gmail.com)
Please remove this line

2020-12-28 11:21 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	$(ROCKCHIP_FIRMWARE_DIR)/tools/mkimage -n rk3399 -T rksd -d $(ROCKCHIP_FIRMWARE_DIR)/bin/rk33/rk3399_ddr_933MHz_v1.24.bin $(UBOOT_OUT)/idbloader_externel.img
AFAIK armbian scripts was used as reference. Please add comment with links to those scripts.

2020-12-28 14:23 UTC, daaaanil81 commented
@rsglobal, review please.

2020-12-28 14:24 UTC, rsglobal commented on platform/uboot/bootscript.cpp
> + EXTENV(bootargs, " earlyprintk console=ttyS2,1500000n8")
Please move this into BoardConfig.mk and enable only for debug builds (See other device as reference)

2020-12-28 14:26 UTC, rsglobal commented on platform/uboot/uboot.mk
> +UBOOT_EMMC_NUMBER := 1
Consider renaming:
UBOOT_EMMC_NUMBER -> UBOOT_MMC_EMMC_INDEX
UBOOT_SD_NUMBER -> UBOOT_MMC_SD_INDEX
?

2020-12-28 14:28 UTC, rsglobal commented on platform/uboot/uboot.mk
> +UBOOT_SD_NUMBER = 1
:= ?

2020-12-28 14:30 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	$(ROCKCHIP_FIRMWARE_DIR)/tools/mkimage -n rk3399 -T rksd -d $(ROCKCHIP_FIRMWARE_DIR)/bin/rk33/rk3399_ddr_933MHz_v1.24.bin $(UBOOT_OUT)/idbloader_externel.img
Please include line number and commit hash into the URL

2020-12-28 14:32 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	dd if=$(UBOOT_OUT)/uboot.img of=$@ seek=16320
Please use inline math `$$(( 16384 - 64 ))`

2020-12-29 09:15 UTC, daaaanil81 commented
@rsglobal,
Please review.

2020-12-29 09:26 UTC, rsglobal commented on platform/uboot/uboot.mk
> +	$(ROCKCHIP_FIRMWARE_DIR)/tools/mkimage -n rk3399 -T rksd -d $(ROCKCHIP_FIRMWARE_DIR)/bin/rk33/rk3399_ddr_933MHz_v1.24.bin $(UBOOT_OUT)/idbloader_externel.img
Please define these variables in opi4.mk and use here:
```
RK_DDR_BLOB:=rk33/rk3399_ddr_933MHz_xxxx.bin
RK_MINILOADER_BLOB:=rk33/rk3399_miniloader_xxxx.bin
RK_BL31_BLOB:=rk33/rk3399_bl31_xxx.elf
```
In

2020-12-29 12:43 UTC, daaaanil81 commented
@rsglobal, 
Please review.

2020-12-29 16:29 UTC, rsglobal requested changes

2020-12-29 16:29 UTC, rsglobal commented on opi4/BoardConfig.mk
> +BOARD_KERNEL_CMDLINE += earlyprintk console=ttyS2,1500000n8
This should be enabled only for debug build.

2020-12-29 16:29 UTC, rsglobal commented on opi4/kernel.config
> +#
Can you give more detailed explanation why to we need each config?

2020-12-29 16:29 UTC, rsglobal commented on platform/uboot/uboot.mk
> +
It would be better to use 1 line space to keep uniform style for this file.

2020-12-29 16:29 UTC, rsglobal commented on platform/uboot/uboot.mk
> +RKTRUST_INI := RK3399TRUST.ini
Consider putting this under "ifdef rockchip", and use full path , like: $(ROCKCHIP_FIRMWARE_DIR)/RKTRUST/RK3399TRUST.ini
and use `nodir` macro to get name only.

2020-12-29 17:30 UTC, rsglobal commented on platform/uboot/uboot.mk
> +RKTRUST_INI := RK3399TRUST.ini
It would be even better to move the `RKTRUST/RK3399TRUST.ini` into opi4.mk,

2021-01-03 18:04 UTC, rsglobal commented
Does emmc deploy/boot work?

2021-01-06 19:04 UTC, daaaanil81 commented
@rsglobal Please review, but i didn't decide problem with ./fastboot reboot-fastboot.

2021-01-08 15:11 UTC, rsglobal requested changes

2021-01-08 15:11 UTC, rsglobal commented on platform/uboot/uboot.mk
> +UBOOT_FRAGMENTS += device/glodroid/platform/common/rockchip/emmc.config
uboot-emmc.config?

2021-01-08 15:11 UTC, rsglobal commented on platform/uboot/uboot.mk
> +ifneq ($(PRODUCT_HAS_EMMC),)
Please use single ` ifeq ($(PRODUCT_BOARD_PLATFORM),rockchip)` block

2021-01-08 15:11 UTC, rsglobal commented on platform/uboot/uboot.mk
> +UBOOT_FRAGMENT_ROCKCHIP_EMMC := device/glodroid/platform/common/rockchip/emmc.config
uboot-emmc.config?

2021-01-08 15:11 UTC, rsglobal commented on platform/uboot/uboot.mk
> +$(UBOOT_BINARY_SD_EMMC): $(UBOOT_BINARY)
Please move under rockchip `ifeq`

2021-01-08 15:11 UTC, rsglobal commented on platform/uboot/uboot.mk
> +$(PRODUCT_OUT)/bootloader-deploy-emmc.img: $(UBOOT_BINARY_SD_EMMC) $(UBOOT_IDBLOADER) $(UBOOT_TRUST)
Please move under rockchip's `ifeq`

2021-01-21 16:44 UTC, daaaanil81 commented
@rsglobal Review please.

2021-01-22 21:22 UTC, rsglobal commented on opi4/kernel.config
> +CONFIG_TYPEC_TCPM=y
I believe we do not need CONFIG_TYPEC, CONFIG_TYPEC_FUSB302, CONFIG_TYPEC_TCPM but instead we need  to set DWC3 to gadget-only.

2021-01-22 21:31 UTC, rsglobal commented
@daaaanil81 ,

Thanks for your work.

Please add origin URL of "opi4/rockchip_defconfig" (including commit SHA) to the commit message

2021-01-22 21:33 UTC, rsglobal commented on platform/uboot/uboot.mk
> +$(PRODUCT_OUT)/bootloader-sd.img: $(UBOOT_IDBLOADER) $(UBOOT_TRUST)
Can you combine next 3 rules into single?
https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_node/make_38.html

2021-01-22 21:38 UTC, rsglobal commented on opi4/kernel.config
> +CONFIG_DRM=y
Please add a comment that: `# We need DRM built-in to show recovery/fastbootd UI which is on initrd`

2021-01-27 16:40 UTC, daaaanil81 commented
@rsglobal  Review please.

2021-01-29 11:18 UTC, daaaanil81 commented
@rsglobal Review please.

2021-01-29 11:26 UTC, rsglobal commented
Looks good. Thank you for all your efforts.

2021-01-29 11:27 UTC, rsglobal approved these changes

2021-01-30 09:42 UTC, merged