pinephone: max brightness bug fix
GloDroid/glodroid_device pull request #16
Opened 2021-02-01 15:49 UTC by SrMrBurchick

Signed-off-by: Serhii Bura <serhii.bura@globallogic.com>

2021-02-01 16:00 UTC, rsglobal requested changes
Hi @SrMrBurchick ,

Thanks for this fix. I've put some comments. Please have a look.

2021-02-01 16:00 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +int const ERROR_CODE = -1;
Consider using -EINVAL instead

2021-02-01 16:00 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +    int convertBrightness(const char* max_brightness_file_path, int current_brightness) {
Consider reading MAX_BRIGHTNESS_FILE once in main() into static global variable.

2021-02-02 07:49 UTC, rsglobal requested changes

2021-02-02 07:49 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +int SYS_MAX_BRIGHTNESS = 0;        // Max brightness readed form system
static?

2021-02-02 07:49 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +uint8_t const BUFFER_SIZE = 16;
These consts aren't shared.
Please put them into the corresponding functions.

2021-02-02 07:49 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +static int sys_read_int(int fd, int& value) {
Please rename to `sysfs_file_read_int` and use `const char *name` instead of `int fd` as an argument.

2021-02-02 07:49 UTC, rsglobal commented on pinephone/lights/lights.cpp
> +                writeLed(LCD_FILE, brightness);
Please change to:
`writeLed(LCD_FILE, convertBrightness(state.color));`

2021-02-02 07:52 UTC, rsglobal commented
I've made some additional review comments. Please have a look.
Also please put a few words into the commit message to explain the issue and the solution.

2021-02-11 13:16 UTC, rsglobal approved these changes
Thank you for this fix.

2021-02-15 14:00 UTC, merged

2021-02-19 19:32 UTC, Shatur95 commented
@SrMrBurchick, I built a new image today from https://github.com/GloDroid/glodroid_manifest, but the brightness level is still low. Is it okay?